# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
# title      Travis CI Build Configuration                   +
# project    northem-dark                                    +
# version                                                    +
# repository https://github.com/arcticicestudio/northem-dark +
# author     Arctic Ice Studio                               +
# email      development@arcticicestudio.com                 +
# copyright  Copyright (C) 2016                              +
# ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
#
# [References]
# Travis CI Documentation
#   (https://docs.travis-ci.com)
language: node_js
sudo: false
cache:
 directories:
    - $HOME/node_modules
before_script:
  - npm install -g gulp
  - npm install
script: gulp compile-css-template sassdoc
